version: '3.9'

services:

  python:
    image: "python" 
    container_name: python
    command: python3 /app/app.py
    volumes:
      - ./volumes/python:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  node:
    image: "node"
    container_name: node
    command: node /app/app.js 
    volumes:
      - ./volumes/node:/app
    depends_on:
      - mongodb

  php:
    image: php:7.4-apache
    container_name: php
    volumes:
      - ./volumes/php:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db 

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080

  db:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: user
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - ./volumes/mongodb:/data/db
    ports: 
      - 27017:27017
 
  redis:
    image: redis:6.2
    container_name: redis
    volumes:
      - ./volumes/redisdb:/data
    ports:
      - 6379:6379